# syntax=docker/dockerfile:1.4
FROM rust:1.80-slim-bullseye AS base

RUN apt update && apt install -y pkg-config libssl-dev
RUN rustup override set nightly && cargo install sqlx-cli --no-default-features --features native-tls,postgres
